# Build matrix / environment variables are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on: http://lint.travis-ci.org/

language: cpp

compiler:
- g++
os:
- linux
addons:
  apt:
    packages:
    - g++-4.9
env:
- DTC_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
- eval "${DTC_EVAL}"

install:
- echo ${CC}
- ${CC} --version
- echo ${CXX}
- ${CXX} --version
- cmake --version
- sudo apt-get install snappy libsnappy-dev zlib1g zlib1g-dev bzip2 liblz4-dev libasan0 openssl libmxml-dev

script:
- mkdir build/
- cd build/
- cmake -DCMAKE_TEST_OPTION=ON ../
- make

after_success:
- cd ../
- cp conf/* dockerfiles/server/
- cp build/src/core/dtcd dockerfiles/server/
- cp build/src/devel/cpp/libdtc.2.so dockerfiles/server/
- cp build/test/* dockerfiles/server/
- cp test/* dockerfiles/server/
- cp src/devel/cpp/dtcapi.h dockerfiles/server/
- cd dockerfiles/server/
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

- docker build -t $DOCKER_USERNAME/server:latest .
- docker push $DOCKER_USERNAME/server:latest
- cd ../agent/
- cp build/src/agent/dtcagent dockerfiles/agent/
- cp conf/agent.xml dockerfiles/agent/
- docker build -t $DOCKER_USERNAME/agent:latest .
- docker push $DOCKER_USERNAME/agent:latest
